routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dash', 'HomeController@dash')->name('dash');
    Route::resource('/book-titles', 'BookTitleController');
    Route::resource('/authors', 'AuthorController');
    Route::resource('/users', 'UserController');
    Route::resource('/book-categories', 'BookCategoryController');
    // books
    Route::post('/books', 'BookController@store')->name('books.store');
    Route::get('/books/{bookTitle}/create', 'BookController@create')->name('books.create');
    Route::put('/books/{book}', 'BookController@update')->name('books.update');
    Route::get('/books/{book}', 'BookController@show')->name('books.show');
    Route::delete('/books/{book}', 'BookController@destroy')->name('books.destroy');
    Route::get('/books/{book}/edit', 'BookController@edit')->name('books.edit');
    // rentals
    Route::post('/book-rental/return/{book}', 'BookRentalController@returnBook')->name('book-rentals.return');
    Route::get('/book-rental/rent/{book}', 'BookRentalController@getRentBook')->name('book-rentals.rent-book');
    Route::post('/book-rental/rent/{book}', 'BookRentalController@rentBook')->name('book-rentals.rent');
});



Route::get('/', 'HomeController@index')->name('home');

resources/views/dash.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <h1 class="display-4 mb-4">
            <i class="fas fa-columns"></i>
            Dashboard
        </h1>
        <div class="row">
            @if(auth()->user()->isAdmin() || auth()->user()->isEmployee())
                <div class="col-xs-12 col-sm-6 col-md-3 mb-4">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ route('users.index') }}">
                                <i class="fas fa-users"></i>
                                Users
                            </a>
                        </div>

                        <div class="card-body display-4 text-right">
                            {{ $usersCount }}
                        </div>
                    </div>
                </div>
            @endif
            <div class="col-xs-12 col-sm-6 col-md-3 mb-4">
                <div class="card">
                    <div class="card-header">
                        <a href="{{ route('authors.index') }}">
                            <i class="fas fa-at"></i>
                            Authors
                        </a>
                    </div>
                    <div class="card-body display-4 text-right">
                        {{ $authorsCount }}
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 mb-4">
                <div class="card">
                    <div class="card-header">
                        <a href="{{ route('book-titles.index') }}">
                            <i class="fas fa-book"></i>
                            Book Titles
                        </a>
                    </div>
                    <div class="card-body display-4 text-right">
                        {{ $bookTitlesCount }}
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 mb-4">
                <div class="card">
                    <div class="card-header">
                        <a href="{{ route('book-categories.index') }}">
                            <i class="fas fa-th-list"></i>
                            Book Categories
                        </a>
                    </div>
                    <div class="card-body display-4 text-right">
                        {{ $bookCategoriesCount }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid" style="min-height: calc(100vh - 55px); background: url({{asset('img/background.jpg')}}); background-size: cover">

    </div>
@endsection