routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dash', 'HomeController@dash')->name('dash');
    Route::resource('/book-titles', 'BookTitleController');
    Route::resource('/authors', 'AuthorController');
    Route::resource('/users', 'UserController');
    Route::resource('/book-categories', 'BookCategoryController');
    // books
    Route::post('/books', 'BookController@store')->name('books.store');
    Route::get('/books/{bookTitle}/create', 'BookController@create')->name('books.create');
    Route::put('/books/{book}', 'BookController@update')->name('books.update');
    Route::get('/books/{book}', 'BookController@show')->name('books.show');
    Route::delete('/books/{book}', 'BookController@destroy')->name('books.destroy');
    Route::get('/books/{book}/edit', 'BookController@edit')->name('books.edit');
    // rentals
    Route::post('/book-rental/return/{book}', 'BookRentalController@returnBook')->name('book-rentals.return');
    Route::get('/book-rental/rent/{book}', 'BookRentalController@getRentBook')->name('book-rentals.rent-book');
    Route::post('/book-rental/rent/{book}', 'BookRentalController@rentBook')->name('book-rentals.rent');
});



Route::get('/', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use SoftDeletes, Notifiable;


    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
    ];

    protected $hidden = [
        'password',
        'remember_token'
    ];


    protected $casts = [
        'email_verified_at' => 'datetime'
    ];

    public function role() {
        return $this->belongsTo(Role::class);
    }

    public function subscriptions() {
        return $this->hasMany(Subscription::class);
    }

    public function bookRentals() {
        return $this->hasMany(BookRental::class);
    }

    public function isAdmin() {
        return $this->role->name === 'admin';
    }

    public function isEmployee() {
        return $this->role->name === 'employee';
    }

    public function scopeOnlyUsers($query) {
        return $query->whereHas('role', function($q) {
            $q->where('name', 'user');
        });
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\Subscription;
use App\User;
use App\Http\Requests\User\Delete;
use App\Http\Requests\User\Store;
use App\Http\Requests\User\Update;
use App\Http\Requests\User\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index(View $request) {
        $usersQuery = User::with(['bookRentals'])->onlyUsers()->latest('id');

        if ($request->query('name'))
            $usersQuery->where('name', 'like', '%' . $request->input('name') . '%');

        if ($request->query('email'))
            $usersQuery->where('email', 'like', '%' . $request->input('email') . '%');

        $users = $usersQuery->paginate();

        return view('users.browse')->with([
            'users' => $users
        ]);
    }

    public function show(View $request, User $user) {
        $user->load([
            'bookRentals.book.bookTitle'
        ]);

        return view('users.view')->with([
            'user' => $user
        ]);
    }

    public function edit(View $request, User $user) {
        $roles = Role::all();

        return view('users.create-edit')->with([
            'user' => $user,
            'roles' => $roles
        ]);
    }

    public function create(View $request) {
        $roles = Role::all();

        return view('users.create-edit')->with([
            'user' => new User(),
            'roles' => $roles
        ]);
    }

    public function store(Store $request) {
        $user = new User();
        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->password = Hash::make('102030');
        $user->role_id = $request->input('role_id');
        $user->save();

        $subscription = new Subscription();
        $subscription->user_id = $user->id;
        $subscription->subscribed_to = now()->addMonth();
        $subscription->save();

        $user->load('subscriptions');

        return redirect(route('users.show', $user->id))
            ->with('success-message', 'Successfully created User');
    }

    public function update(Update $request, User $user) {
        $user->update($request->all());

        $user->load('subscriptions');

        return redirect(route('users.show', $user->id))
            ->with('success-message', 'Successfully updated User');
    }

    public function destroy(Delete $request, User $user) {
        $user->delete();

        return redirect(route('users.index'))->with([
            'danger-message' => 'Successfully deleted User'
        ]);
    }
}

resources/views/users/browse.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">

        <div class="row justify-content-end">
            <a href="{{ route('users.create') }}" class="btn btn-primary col-sm-2">Add New</a>
        </div>

        <h1 class="display-3 mb-4">
            <i class="fas fa-users"></i>
            Users
        </h1>

        <form class="py-3 px-3 row justify-content-between" action="{{ route('users.index') }}" method="GET">
            <div class="form-group">
                <label for="title">Name</label>
                <input class="form-control" type="text" name="name"
                       value="{{ request()->query('name') }}"
                       placeholder="Filter by name"
                />
            </div>
            <div class="form-group">
                <label for="title">Email</label>
                <input class="form-control" type="text" name="email"
                       value="{{ request()->query('email') }}"
                       placeholder="Filter by email"
                />
            </div>
            <div class="col-sm-2 flex-center">
                <button type="submit" class="btn btn-primary btn-block">
                    Filter
                    <i class="ml-2 fas fa-search"></i>
                </button>
            </div>
        </form>

        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Rented Books</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <th scope="row">{{ $user->id }}</th>
                    <td>
                        <a href="{{ route('users.show', $user->id) }}">
                            {{ $user->name }}
                        </a>
                    </td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->bookRentals->count() > 0 ? $user->bookRentals->count() : 'n/a' }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $users->links() }}
    </div>
@endsection

resources/views/users/create-edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <div class="mb-3">
            <a href="{{ $user->id ? route('users.show', $user->id) : route('users.index') }}" class="mb-5">
                <i class="fas fa-arrow-left"></i>
                Back
            </a>
        </div>


        <h1 class="display-3">
            <i class="fas fa-user"></i>
            {{ $user->id ? 'Edit' : 'Create' }} User
        </h1>

        <form method="POST" action="{{ $user->id ? route('users.update', $user->id) : route('users.store') }}">
            @csrf
            @if($user->id)
                @method('PUT')
            @endif
            @if(auth()->user()->isAdmin())
                <div class="form-group">
                    <label for="role_id">Role</label>
                    <select class="form-control @error('role_id') is-invalid @enderror" name="role_id">
                        <option value="">Select role</option>
                        @foreach($roles as $role)
                            <option value="{{ $role->id }}"
                                    @if($role->id == old('role_id', $user->role_id)) selected @endif
                            >
                                {{ ucfirst($role->name) }}
                            </option>
                        @endforeach
                    </select>
                    @error('role_id')
                    <div class="invalid-feedback">{{ $errors->first('role_id') }}</div>
                    @enderror
                </div>
            @else
                <input type="hidden" name="role_id" value="{{ $roles->where('name', 'user')->first()->id }}" />
            @endif
            <div class="form-group">
                <label for="name">Name</label>
                <input class="form-control @error('name') is-invalid @enderror" type="text" name="name"
                       value="{{old('name', $user->name)}}"
                       placeholder="Enter name"
                />
                @error('name')
                    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input class="form-control @error('email') is-invalid @enderror" type="email" name="email"
                       value="{{old('email', $user->email)}}"
                       placeholder="Enter email"
                />
                @error('email')
                    <div class="invalid-feedback">{{ $errors->first('email') }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/users/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">

        <div class="mb-3">
            <a href="{{ route('users.index') }}" class="mb-5">
                <i class="fas fa-arrow-left"></i>
                All Users
            </a>
        </div>

        <div class="row justify-content-end">
            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary col-sm-2">
                Edit
                <i class="ml-2 fas fa-edit"></i>
            </a>
            <form action="{{ route('users.destroy', $user->id) }}" METHOD="post" class="col-sm-2 deleteForm">
                @method('delete')
                @csrf
                <button type="submit" class="btn btn-danger btn-block ">
                    Delete
                    <i class="ml-2 fas fa-trash-alt"></i>
                </button>
            </form>
        </div>

        <h1 class="display-3">
            <i class="fas fa-user"></i>
            {{ $user->name  }}
        </h1>

        <div>Email</div>
        <h5 class="font-weight-bold">{{ $user->email }}</h5>


        <hr />

        <h4 class="mt-5">Rented Books</h4>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th>Book Title</th>
                <th>Book</th>
                <th>Rented At</th>
                <th>Returned At</th>
            </tr>
            </thead>
            <tbody>
            @foreach($user->bookRentals as $bookRental)
                <tr>
                    <td scope="row">{{ $bookRental->id }}</td>
                    <td>
                        <a href="{{ route('book-titles.show', $bookRental->book->book_title_id) }}">
                            {{ $bookRental->book->bookTitle->title }}
                        </a>
                    </td>
                    <td>
                        <a href="{{ route('books.show', $bookRental->book_id) }}">
                            {{ $bookRental->book->barcode }}
                        </a>
                    </td>
                    <td>{{ $bookRental->book->created_at->format('d.m.Y.') }}</td>
                    <td>
                        @if($bookRental->is_returned)
                            {{ $bookRental->returned_at->format('d.m.Y.') }}
                        @else
                            <i class="fas fa-times text-danger"></i>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection