routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dash', 'HomeController@dash')->name('dash');
    Route::resource('/book-titles', 'BookTitleController');
    Route::resource('/authors', 'AuthorController');
    Route::resource('/users', 'UserController');
    Route::resource('/book-categories', 'BookCategoryController');
    // books
    Route::post('/books', 'BookController@store')->name('books.store');
    Route::get('/books/{bookTitle}/create', 'BookController@create')->name('books.create');
    Route::put('/books/{book}', 'BookController@update')->name('books.update');
    Route::get('/books/{book}', 'BookController@show')->name('books.show');
    Route::delete('/books/{book}', 'BookController@destroy')->name('books.destroy');
    Route::get('/books/{book}/edit', 'BookController@edit')->name('books.edit');
    // rentals
    Route::post('/book-rental/return/{book}', 'BookRentalController@returnBook')->name('book-rentals.return');
    Route::get('/book-rental/rent/{book}', 'BookRentalController@getRentBook')->name('book-rentals.rent-book');
    Route::post('/book-rental/rent/{book}', 'BookRentalController@rentBook')->name('book-rentals.rent');
});



Route::get('/', 'HomeController@index')->name('home');

app/BookTitle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class BookTitle extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title',
        'isbn',
        'file',
        'book_category_id',
        'author_id'
    ];

    public function author() {
        return $this->belongsTo(Author::class)->withTrashed();
    }

    public function bookCategory() {
        return $this->belongsTo(BookCategory::class);
    }

    public function books() {
        return $this->hasMany(Book::class);
    }

    public function getAvailableBooksCountAttribute() {
        if ($this->relationLoaded('books'))
            $this->load('books');

        return $this->books()->where('is_available', true)->count();
    }

    public function tryFindImage() {
        $url = "http://covers.openlibrary.org/b/isbn/$this->isbn-L.jpg";
        $contents = file_get_contents($url);

        $path = 'book-titles/'.substr($url, strrpos($url, '/') + 1);

        Storage::disk('public')->put($path, $contents);

        $this->file = $path;

        return $this->save();
    }
}

app/Http/Controllers/BookTitleController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use App\BookCategory;
use App\BookTitle;
use App\Http\Requests\BookTitle\Create;
use App\Http\Requests\BookTitle\Delete;
use App\Http\Requests\BookTitle\Edit;
use App\Http\Requests\BookTitle\Store;
use App\Http\Requests\BookTitle\Update;
use Illuminate\Http\Request;

class BookTitleController extends Controller
{
    public function index(Request $request) {
        $bookTitlesQuery = BookTitle::with(['author', 'bookCategory', 'books'])->latest('id');

        if ($request->query('author_id'))
            $bookTitlesQuery->where('author_id', $request->input('author_id'));

        if ($request->query('book_category_id'))
            $bookTitlesQuery->where('book_category_id', $request->input('book_category_id'));

        if ($request->query('title'))
            $bookTitlesQuery->where('title', 'like', '%' . $request->input('title') . '%');

        $bookTitles = $bookTitlesQuery->paginate();
        $bookCategories = BookCategory::all();
        $authors = Author::all();

        return view('book-titles.browse')->with([
            'bookTitles' => $bookTitles,
            'authors' => $authors,
            'bookCategories' => $bookCategories
        ]);
    }

    public function show(BookTitle $bookTitle) {
        $bookTitle->load([
            'bookCategory',
            'author',
            'books'
        ]);

        return view('book-titles.view')->with([
            'bookTitle' => $bookTitle
        ]);
    }

    public function edit(Edit $request, BookTitle $bookTitle) {
        $bookCategories = BookCategory::all();
        $authors = Author::all();

        return view('book-titles.create-edit')->with([
            'authors' => $authors,
            'bookTitle' => $bookTitle,
            'bookCategories' => $bookCategories
        ]);
    }

    public function create(Create $request) {
        $bookCategories = BookCategory::all();
        $authors = Author::all();

        return view('book-titles.create-edit')->with([
            'bookTitle' => new BookTitle(),
            'authors' => $authors,
            'bookCategories' => $bookCategories
        ]);
    }

    public function store(Store $request) {
        $bookTitle = BookTitle::create($request->all());

        $bookTitle->tryFindImage();

        return redirect(route('book-titles.show', $bookTitle->id))
            ->with('success-message', 'Successfully created Book title');
    }

    public function update(Update $request, BookTitle $bookTitle) {
        $isbnUpdated = $request->input('isbn') && $request->input('isbn') !== $bookTitle->isbn;

        $bookTitle->update($request->all());

        if ($isbnUpdated) {
            $bookTitle->tryFindImage();
        }

        return redirect(route('book-titles.show', $bookTitle->id))
            ->with('success-message', 'Successfully updated Book title');
    }

    public function destroy(Delete $request, BookTitle $bookTitle) {
        $bookTitle->delete();

        return redirect(route('book-titles.index'))->with([
            'danger-message' => 'Successfully deleted Book Title'
        ]);
    }
}

resources/views/book-titles/browse.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        @if(auth()->user()->isAdmin() || auth()->user()->isEmployee())
        <div class="row justify-content-end">
            <a href="{{ route('book-titles.create') }}" class="btn btn-primary col-sm-2">Add New</a>
        </div>
        @endif

        <h1 class="display-3 mb-4">
            <i class="fas fa-book"></i>
            Book Titles
        </h1>

        <form class="py-3 px-3 row justify-content-between" action="{{ route('book-titles.index') }}" method="GET">
            <div class="form-group">
                <label for="title">Title</label>
                <input class="form-control" type="text" name="title"
                       value="{{ request()->query('title') }}"
                       placeholder="Filter by title"
                />
            </div>
            <div class="form-group">
                <label for="author_id">Author</label>
                <select class="form-control" name="author_id">
                    <option value="">Filter by author</option>
                    @foreach($authors as $author)
                        <option value="{{ $author->id }}"
                                @if($author->id == request()->query('author_id')) selected @endif
                        >
                            {{ $author->name }}
                        </option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="book_category_id">Book Category</label>
                <select class="form-control" name="book_category_id">
                    <option value="">Filter by category</option>
                    @foreach($bookCategories as $category)
                        <option value="{{ $category->id }}"
                                @if($category->id == request()->query('book_category_id')) selected @endif
                        >
                            {{ $category->name }}
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="col-sm-2 flex-center">
                <button type="submit" class="btn btn-primary btn-block">
                    Filter
                    <i class="ml-2 fas fa-search"></i>
                </button>
            </div>
        </form>

        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Category</th>
                <th scope="col">Author</th>
                <th scope="col">Available</th>
            </tr>
            </thead>
            <tbody>
            @foreach($bookTitles as $bookTitle)
                <tr>
                    <td scope="row">{{ $bookTitle->id }}</td>
                    <td><img src="{{ asset('storage/'.$bookTitle->file) }}" alt="Book Cover" width="50px"></td>
                    <td>
                        <a href="{{ route('book-titles.show', $bookTitle->id) }}">
                            {{ $bookTitle->title }}
                        </a>
                    </td>
                    <td>{{ $bookTitle->bookCategory->name }}</td>
                    <td>{{ $bookTitle->author->name }}</td>
                    <td>{{ $bookTitle->availableBooksCount }} / {{ $bookTitle->books->count() }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $bookTitles->links() }}
    </div>
@endsection

resources/views/book-titles/create-edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <div class="mb-3">
            <a href="{{ $bookTitle->id ? route('book-titles.show', $bookTitle->id) : route('book-titles.index') }}" class="mb-5">
                <i class="fas fa-arrow-left"></i>
                Back
            </a>
        </div>


        <h1 class="display-3">
            <i class="fas fa-book"></i>
            {{ $bookTitle->id ? 'Edit' : 'Create' }} Book Title
        </h1>

        <form method="POST" action="{{ $bookTitle->id ? route('book-titles.update', $bookTitle->id) : route('book-titles.store') }}">
            @csrf
            @if($bookTitle->id)
                @method('PUT')
            @endif
            <div class="form-group">
                <label for="title">Title</label>
                <input class="form-control @error('title') is-invalid @enderror" type="text" name="title"
                       value="{{old('title', $bookTitle->title)}}"
                       placeholder="Enter title"
                />
                @error('title')
                <div class="invalid-feedback">{{ $errors->first('title') }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="isbn">ISBN</label>
                <input class="form-control @error('isbn') is-invalid @enderror" type="text" name="isbn"
                       value="{{old('isbn', $bookTitle->isbn)}}"
                       placeholder="Enter ISBN"
                />
                @error('isbn')
                <div class="invalid-feedback">{{ $errors->first('isbn') }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="book_category_id">Category</label>
                <select class="form-control @error('book_category_id') is-invalid @enderror" name="book_category_id">
                    <option value="">Select category</option>
                    @foreach($bookCategories as $category)
                        <option value="{{ $category->id }}"
                                @if($category->id == old('book_category_id', $bookTitle->book_category_id)) selected @endif
                        >
                            {{ $category->name }}
                        </option>
                    @endforeach
                </select>
                @error('book_category_id')
                <div class="invalid-feedback">{{ $errors->first('book_category_id') }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="author_id">Author</label>
                <select class="form-control @error('author_id') is-invalid @enderror" name="author_id">
                    <option value="">Select author</option>
                    @foreach($authors as $author)
                        <option value="{{ $author->id }}"
                                @if($author->id == old('author_id', $bookTitle->author_id)) selected @endif
                        >
                            {{ $author->name }}
                        </option>
                    @endforeach
                </select>
                @error('author_id')
                <div class="invalid-feedback">{{ $errors->first('author_id') }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/book-titles/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">

        <div class="mb-3">
            <a href="{{ route('book-titles.index') }}" class="mb-5">
                <i class="fas fa-arrow-left"></i>
                All Book Titles
            </a>
        </div>

        <div class="row justify-content-end">
            @if(auth()->user()->isAdmin() || auth()->user()->isEmployee())
            <a href="{{ route('book-titles.edit', $bookTitle->id) }}" class="btn btn-primary col-sm-2">
                Edit
                <i class="ml-2 fas fa-edit"></i>
            </a>
            @endif
            @if(auth()->user()->isAdmin())
                <form action="{{ route('book-titles.destroy', $bookTitle->id) }}" METHOD="post" class="col-sm-2 deleteForm">
                    @method('delete')
                    @csrf
                    <button type="submit" class="btn btn-danger btn-block ">
                        Delete
                        <i class="ml-2 fas fa-trash-alt"></i>
                    </button>
                </form>
            @endif
        </div>

        <div class="row  mt-4">
            <div class="flex-shrink-0">
                <img src="{{ asset('storage/'.$bookTitle->file) }}" alt="Book Cover" height="400px">
            </div>
            <div class="flex-grow-1 pl-4">
                <h1 class="display-3">
                    <i class="fas fa-book"></i>
                    {{ $bookTitle->title  }}
                </h1>
                <div>Author</div>
                <h5 class="font-weight-bold">
                    <a href="{{ route('authors.show', $bookTitle->author_id) }}">
                        {{ $bookTitle->author->name }}
                    </a>
                </h5>
                <div>Book Category</div>
                <h5 class="font-weight-bold">
                    <a href="{{ route('book-categories.show', $bookTitle->book_category_id) }}">
                        {{ $bookTitle->bookCategory->name }}
                    </a>
                </h5>
            </div>
        </div>

        <hr />

        <h4 class="mt-5">
            <i class="fas fa-book-open"></i>
            Books
        </h4>
        @if(auth()->user()->isAdmin() || auth()->user()->isEmployee())
        <div class="row justify-content-end mb-2">
            <a href="{{ route('books.create', $bookTitle->id) }}" class="btn btn-primary col-sm-2">Add New</a>
        </div>
        @endif

        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th>Publication</th>
                <th>Year</th>
                <th>Available</th>
                @if(auth()->user()->isAdmin() || auth()->user()->isEmployee())
                <th></th>
                @endif
            </tr>
            </thead>
            <tbody>
            @foreach($bookTitle->books as $book)
                <tr>
                    <td>
                        <a href="{{ route('books.show', $book->id) }}">
                            {{ $book->barcode }}
                        </a>
                    </td>
                    <td>{{ $book->publication }}</td>
                    <td>{{ $book->publication_year }}</td>
                    <td>
                        @if($book->is_available)
                            <i class="fas fa-check text-success"></i>
                        @else
                            <i class="fas fa-times text-danger"></i>
                        @endif
                    </td>
                    <td>
                        <div class="form-inline">
                            @if(auth()->user()->isAdmin() || auth()->user()->isEmployee())
                            <a href="{{ route('books.edit', $book->id) }}" class="btn btn-primary">
                                <i class="fas fa-edit"></i>
                            </a>
                            @endif
                            @if(auth()->user()->isAdmin())
                            <form action="{{ route('books.destroy', $book->id) }}" METHOD="post" class="deleteForm">
                                @method('delete')
                                @csrf
                                <button type="submit" class="ml-2 btn btn-danger">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>
                            @endif
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection