routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dash', 'HomeController@dash')->name('dash');
    Route::resource('/book-titles', 'BookTitleController');
    Route::resource('/authors', 'AuthorController');
    Route::resource('/users', 'UserController');
    Route::resource('/book-categories', 'BookCategoryController');
    // books
    Route::post('/books', 'BookController@store')->name('books.store');
    Route::get('/books/{bookTitle}/create', 'BookController@create')->name('books.create');
    Route::put('/books/{book}', 'BookController@update')->name('books.update');
    Route::get('/books/{book}', 'BookController@show')->name('books.show');
    Route::delete('/books/{book}', 'BookController@destroy')->name('books.destroy');
    Route::get('/books/{book}/edit', 'BookController@edit')->name('books.edit');
    // rentals
    Route::post('/book-rental/return/{book}', 'BookRentalController@returnBook')->name('book-rentals.return');
    Route::get('/book-rental/rent/{book}', 'BookRentalController@getRentBook')->name('book-rentals.rent-book');
    Route::post('/book-rental/rent/{book}', 'BookRentalController@rentBook')->name('book-rentals.rent');
});



Route::get('/', 'HomeController@index')->name('home');

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Author extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'birth_year',
        'birth_country',
        'bio'
    ];

    public function bookTitles() {
        return $this->hasMany(BookTitle::class);
    }
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use App\Http\Requests\Author\Create;
use App\Http\Requests\Author\Delete;
use App\Http\Requests\Author\Edit;
use App\Http\Requests\Author\Store;
use App\Http\Requests\Author\Update;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    public function index(Request $request) {
        $authorsQuery = Author::with(['bookTitles.bookCategory'])->latest('id');

        if ($request->query('birth_country'))
            $authorsQuery->where('birth_country', 'like', '%' . $request->input('birth_country') . '%');

        if ($request->query('name'))
            $authorsQuery->where('name', 'like', '%' . $request->input('name') . '%');

        $authors = $authorsQuery->paginate();

        return view('authors.browse')->with([
            'authors' => $authors
        ]);
    }

    public function show(Author $author) {
        $author->load('bookTitles.bookCategory');

        return view('authors.view')->with([
            'author' => $author
        ]);
    }

    public function edit(Edit $request, Author $author) {
        return view('authors.create-edit')->with([
            'author' => $author
        ]);
    }

    public function create(Create $request) {
        return view('authors.create-edit')->with([
            'author' => new Author()
        ]);
    }

    public function store(Store $request) {
        $author = Author::create($request->all());

        return redirect(route('authors.show', $author->id))
            ->with('success-message', 'Successfully created Author');
    }

    public function update(Update $request, Author $author) {
        $author->update($request->all());

        return redirect(route('authors.show', $author->id))
            ->with('success-message', 'Successfully updated Author');
    }

    public function destroy(Delete $request, Author $author) {
        $author->delete();

        return redirect(route('authors.index'))->with([
            'danger-message' => 'Successfully deleted Author'
        ]);
    }
}

resources/views/authors/browse.blade.php
@extends('layouts.app')

@section('content')
   <div class="container mt-4">
       @if(auth()->user()->isAdmin() || auth()->user()->isEmployee())
           <div class="row justify-content-end">
               <a href="{{ route('authors.create') }}" class="btn btn-primary col-sm-2">Add New</a>
           </div>
       @endif
       <h1 class="display-3 mb-4">
           <i class="fas fa-at"></i>
           Authors
       </h1>

       <form class="py-3 px-3 row justify-content-between" action="{{ route('authors.index') }}" method="GET">
           <div class="form-group">
               <label for="name">Name</label>
               <input class="form-control" type="text" name="name"
                      value="{{ request()->query('name') }}"
                      placeholder="Filter by name"
               />
           </div>
           <div class="form-group">
               <label for="birth_country">Birth Country</label>
               <input class="form-control" type="text" name="birth_country"
                      value="{{ request()->query('birth_country') }}"
                      placeholder="Filter by birth country"
               />
           </div>
           <div class="col-sm-2 flex-center">
               <button type="submit" class="btn btn-primary btn-block">
                   Filter
                   <i class="ml-2 fas fa-search"></i>
               </button>
           </div>
       </form>

       <table class="table">
           <thead>
           <tr>
               <th scope="col">#</th>
               <th scope="col">Name</th>
               <th scope="col">Birth Year</th>
               <th scope="col">Birth Country</th>
               <th scope="col">Book titles</th>
           </tr>
           </thead>
           <tbody>
           @foreach($authors as $author)
               <tr>
                   <td>{{ $author->id }}</td>
                   <td>
                       <a href="{{ route('authors.show', $author->id) }}">
                           {{ $author->name }}
                       </a>
                   </td>
                   <td>{{ $author->birth_year }}</td>
                   <td>{{ $author->birth_country }}</td>
                   <td>{{ $author->bookTitles->count() }}</td>
               </tr>
           @endforeach
           </tbody>
       </table>
       {{ $authors->links() }}
   </div>
@endsection

resources/views/authors/create-edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <div class="mb-3">
            <a href="{{ $author->id ? route('authors.show', $author->id) : route('authors.index') }}" class="mb-5">
                <i class="fas fa-arrow-left"></i>
                Back
            </a>
        </div>


        <h1 class="display-3">
            <i class="fas fa-at"></i>
            {{ $author->id ? 'Edit' : 'Create' }} Author
        </h1>

        <form method="POST" action="{{ $author->id ? route('authors.update', $author->id) : route('authors.store') }}">
            @csrf
            @if($author->id)
                @method('PUT')
            @endif
            <div class="form-group">
                <label for="name">Name</label>
                <input class="form-control @error('name') is-invalid @enderror" type="text" name="name"
                       value="{{old('name', $author->name)}}"
                       placeholder="Enter name"
                />
                @error('name')
                    <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="birth_year">Birth Year</label>
                <input class="form-control @error('birth_year') is-invalid @enderror" type="number" name="birth_year"
                       min="1950" max="{{ now()->year - 15 }}"
                       value="{{old('birth_year', $author->birth_year)}}"
                       placeholder="Enter birth year"
                />
                @error('birth_year')
                    <div class="invalid-feedback">{{ $errors->first('birth_year') }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="birth_country">Birth Country</label>
                <input class="form-control @error('birth_country') is-invalid @enderror" type="text" name="birth_country"
                       value="{{old('birth_country', $author->birth_country)}}"
                       placeholder="Enter birth country"
                />
                @error('birth_country')
                    <div class="invalid-feedback">{{ $errors->first('birth_country') }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="bio">Bio</label>
                <textarea class="form-control @error('bio') is-invalid @enderror"
                      name="bio" placeholder="Enter bio"
                >{{old('bio', $author->bio)}}</textarea>

                @error('bio')
                    <div class="invalid-feedback">{{ $errors->first('bio') }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/authors/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">

        <div class="mb-3">
            <a href="{{ route('authors.index') }}" class="mb-5">
                <i class="fas fa-arrow-left"></i>
                All Authors
            </a>
        </div>

        <div class="row justify-content-end">
            @if(auth()->user()->isAdmin() || auth()->user()->isEmployee())
                <a href="{{ route('authors.edit', $author->id) }}" class="btn btn-primary col-sm-2">Edit</a>
            @endif
            @if(auth()->user()->isAdmin())
                <form action="{{ route('authors.destroy', $author->id) }}" METHOD="post" class="col-sm-2 deleteForm">
                    @method('delete')
                    @csrf
                    <button type="submit" class="btn btn-danger btn-block ">
                        Delete
                        <i class="ml-2 fas fa-trash-alt"></i>
                    </button>
                </form>
            @endif
        </div>

        <h1 class="display-3">
            <i class="fas fa-at"></i>
            {{ $author->name  }}
        </h1>

        <div>Birth year</div>
        <h5 class="font-weight-bold">{{ $author->birth_year }}</h5>
        <div>Birth country</div>
        <h5 class="font-weight-bold">{{ $author->birth_country }}</h5>
        <div>Bio</div>
        <h5 class="font-weight-bold">{{ $author->bio }}</h5>

        <hr />

        <h4 class="mt-5">Book Titles</h4>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th>Title</th>
                <th>Category</th>
            </tr>
            </thead>
            <tbody>
            @foreach($author->bookTitles as $bookTitle)
                <tr>
                    <th scope="row">{{ $bookTitle->id }}</th>
                    <th>
                        <a href="{{ route('book-titles.show', $bookTitle->id) }}">
                            {{ $bookTitle->title }}
                        </a>
                    </th>
                    <th>{{ $bookTitle->bookCategory->name }}</th>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection